### ISSUE TITLE
Add Delegated Administration?

### ISSUE THREAD

**Issue by ckoppelman** [amtrack/sfdx-browserforce-plugin#248]
Delegated Administration groups is one of the most difficult things for us to consistently manage across environments, and it is crucial for user experience.  Is there a way to add Delegated Adminstration to this?

**Comment by amtrack** [comment]
@ckoppelman I've to admit that I'm not familiar with "Delegated Administration".

From what I see, it is listed as [unsupported in Metadata](https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_unsupported_types.htm) but since API v36.0 there is a [DelegateGroup](https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_delegategroup.htm) MetadataType.

Can you please explain what gap there is between `DelegateGroup` and "Delegated Administration" in the Setup Menu?

**Comment by ckoppelman** [comment]
Sorry, my primary problem with `DelegateGroup`s is actually covered in Metadata, but not in the best way.  I am closing this!  Sorry, and thanks for the cool project!
