### ISSUE TITLE
Topic: Plugin Development

### ISSUE THREAD

**Issue by ozanbotanls** [amtrack/sfdx-browserforce-plugin#498]
Hey @amtrack! 

Quick question.. I have some unique use cases that I want to automate by applying browserforce. Given these are not as generic as the provided commands here, it is not a good idea to have them public really. How can we port our own settings into your plugin? Only way is to fork the repo and work on our own unique version?

Cheers

**Comment by amtrack** [comment]
@ozanbotanls I think starting with a private fork is a good idea.

I had plans to make this pluggable and I still would love to do that, but due to a lack of time I wasn't able to do this yet.
There are also quite different approaches and I just don't know yet which way to go.

If you want to push this topic by contributing thoughts and/or code I'm open to work on that.
